{{ if .Values.options.external }}


{{ if .Values.options.san }}

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: "{{ $.Release.Name }}-cert"
spec:
  domains:
{{ range .Values.domains }}
  - {{ .domain }}{{ end }}


{{ else }}

{{ range .Values.domains }}
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: "{{ .name }}-{{ $.Release.Name }}-cert"
spec:
  domains:
  - {{ .domain }}
---
{{ end }}

{{ end }}


{{ end }}

{{ if and .Values.options.internalTLS .Values.internalTLS.domains .Values.internalTLS.certName}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.internalTLS.certName}}
  namespace: default
spec:
  secretName: {{.Values.internalTLS.certName}}
  issuerRef:
    name: letsencrypt-prod
  dnsNames: 
  {{ range .Values.internalTLS.domains }}
    - "{{ . }}"
  {{ end }}
{{ end }}
