apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    {{ if .Values.service.backendConfig }}
    beta.cloud.google.com/backend-config: '{"ports": {"{{ .Values.service.port }}":"{{ .Values.service.backendConfig }}"}}' 
    {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{ if .Values.options.internalTLS }}
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    {{end}}
    {{ if .Values.service.secondaryPort }}
    - port: {{ .Values.service.secondaryPort }}
      targetPort: {{ .Values.service.secondaryPort }}
      protocol: TCP
      name: {{ .Values.service.secondaryPortName }}
    {{ end }}
  selector: 
    app: {{ .Release.Name }}
